/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if the server is running and healthy
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Server is healthy */
                            message: string;
                            /**
                             * @example ok
                             * @enum {string}
                             */
                            status: "ok";
                            /** @example 2025-10-31T10:30:00.000Z */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hello endpoint
         * @description Simple health/test endpoint that returns a greeting message
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["HelloResponse"];
                            error?: null;
                            message?: null;
                            meta?: components["schemas"]["Meta"] & (Record<string, never> | null);
                            /** @enum {boolean} */
                            success: true;
                            /** @example 00-1234567890abcdef-1234567890abcdef-01 */
                            traceId: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create user
         * @description Register a new user account
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserBody"];
                };
            };
            responses: {
                /** @description User created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CreateUserResponse"];
                            error?: null;
                            message?: null;
                            meta?: components["schemas"]["Meta"] & (Record<string, never> | null);
                            /** @enum {boolean} */
                            success: true;
                            /** @example 00-1234567890abcdef-1234567890abcdef-01 */
                            traceId: string;
                        };
                    };
                };
                /** @description Validation Error - Invalid request body, params, or query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Conflict - Resource already exists or conflict occurred */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error - Unexpected server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by ID
         * @description Retrieve user information by ID. Users can only access their own data.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserData"];
                            error?: null;
                            message?: null;
                            meta?: components["schemas"]["Meta"] & (Record<string, never> | null);
                            /** @enum {boolean} */
                            success: true;
                            /** @example 00-1234567890abcdef-1234567890abcdef-01 */
                            traceId: string;
                        };
                    };
                };
                /** @description Unauthorized - Invalid or missing authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - Insufficient permissions for this resource */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found - Requested resource does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error - Unexpected server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppError: {
            context?: {
                [key: string]: unknown;
            };
            message: string;
            resourceId?: number;
            /** @example 2025-10-31T10:30:00.000Z */
            timestamp?: string;
            userId?: number;
            /** @enum {string} */
            code: "COMMAND_EXECUTION_ERROR";
        } | {
            context?: {
                [key: string]: unknown;
            };
            message: string;
            resourceId?: number;
            /** @example 2025-10-31T10:30:00.000Z */
            timestamp?: string;
            userId?: number;
            /** @enum {string} */
            code: "CONFLICT";
            /** @enum {string} */
            conflictType: "email";
            email?: string;
        } | {
            context?: {
                [key: string]: unknown;
            };
            message: string;
            resourceId: number;
            /** @example 2025-10-31T10:30:00.000Z */
            timestamp?: string;
            userId?: number;
            /** @enum {string} */
            code: "FORBIDDEN";
            /** @enum {string} */
            resourceType: "auth" | "comment" | "post" | "user";
        } | {
            context?: {
                [key: string]: unknown;
            };
            message: string;
            resourceId?: number;
            /** @example 2025-10-31T10:30:00.000Z */
            timestamp?: string;
            userId?: number;
            /** @enum {string} */
            code: "INTERNAL_ERROR";
        } | {
            context?: {
                [key: string]: unknown;
            };
            message: string;
            resourceId: number;
            /** @example 2025-10-31T10:30:00.000Z */
            timestamp?: string;
            userId?: number;
            /** @enum {string} */
            code: "NOT_FOUND";
            /** @enum {string} */
            resourceType: "auth" | "comment" | "post" | "user";
        } | {
            context?: {
                [key: string]: unknown;
            };
            message: string;
            resourceId?: number;
            /** @example 2025-10-31T10:30:00.000Z */
            timestamp?: string;
            userId?: number;
            /** @enum {string} */
            code: "UNAUTHORIZED";
        } | {
            context?: {
                [key: string]: unknown;
            };
            message: string;
            resourceId?: number;
            /** @example 2025-10-31T10:30:00.000Z */
            timestamp?: string;
            userId?: number;
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            field: string;
        };
        ErrorResponse: {
            data?: null;
            error: components["schemas"]["AppError"];
            /** @example An error occurred */
            message: string;
            meta?: null;
            /** @enum {boolean} */
            success: false;
            /** @example 00-1234567890abcdef-1234567890abcdef-01 */
            traceId: string;
        };
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 10 */
            size: number;
            /** @example 100 */
            total: number;
        };
        CursorMeta: {
            /** @example abc123 */
            next_cursor?: string | null;
            /** @example def456 */
            previous_cursor?: string | null;
        };
        Meta: {
            cursor?: components["schemas"]["CursorMeta"] & (Record<string, never> | null);
            pagination?: components["schemas"]["PaginationMeta"] & (Record<string, never> | null);
        };
        HelloResponse: {
            /** @example Hello from API */
            message: string;
        };
        CreateUserResponse: {
            /**
             * Format: email
             * @example jane.doe@example.com
             */
            email: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @example Jane Doe */
            name: string | null;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            token: string;
        };
        CreateUserBody: {
            /**
             * Format: email
             * @example jane.doe@example.com
             */
            email: string;
            /** @example Jane Doe */
            name: string;
            /** @example securePassword123 */
            password: string;
        };
        UserData: {
            /**
             * Format: date
             * @example 2025-10-29T10:30:00.000Z
             */
            createdAt: string | null;
            /**
             * Format: email
             * @example jane.doe@example.com
             */
            email: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @example Jane Doe */
            name: string | null;
            /**
             * Format: date
             * @example 2025-10-29T10:30:00.000Z
             */
            updatedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
