/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello_api_v1_hello_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppResponse[CreateUserResponse] */
        AppResponse_CreateUserResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["CreateUserResponse"] | null;
            /** Message */
            message?: string | null;
            meta?: components["schemas"]["Meta"] | null;
            error?: components["schemas"]["ErrorInfo"] | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** AppResponse[HelloResponse] */
        AppResponse_HelloResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["HelloResponse"] | null;
            /** Message */
            message?: string | null;
            meta?: components["schemas"]["Meta"] | null;
            error?: components["schemas"]["ErrorInfo"] | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** User Name */
            user_name: string;
            /** User Surname */
            user_surname: string;
            /** Password */
            password: string;
        };
        /** CreateUserResponse */
        CreateUserResponse: {
            /** User Name */
            user_name: string;
            /** User Surname */
            user_surname: string;
            /** Email */
            email: string;
        };
        /** CursorMeta */
        CursorMeta: {
            /** Next Cursor */
            next_cursor?: string | null;
            /** Previous Cursor */
            previous_cursor?: string | null;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "HTTP_ERROR" | "INTERNAL_ERROR" | "RESOURCE_NOT_FOUND" | "CONFLICT";
        /** ErrorInfo */
        ErrorInfo: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Detail */
            detail?: string | {
                [key: string]: unknown;
            } | unknown[] | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][];
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field?: string | null;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelloResponse */
        HelloResponse: {
            /** Message */
            message: string;
        };
        /** Meta */
        Meta: {
            pagination?: components["schemas"]["PaginationMeta"] | null;
            cursor?: components["schemas"]["CursorMeta"] | null;
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hello_api_v1_hello_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponse_HelloResponse_"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponse_CreateUserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
