openapi: 3.1.0
info:
  title: Backend-AI API
  description: API contract between Backend (Express) and AI Service (FastAPI)
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:8000/api/v1
    description: Local development server
  - url: https://ai.example.com/v1
    description: Production server

tags:
  - name: Health
    description: Health check endpoints
  - name: AI
    description: AI processing endpoints

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Returns the health status of the AI service
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
                  weaviate_status:
                    type: string
                    example: connected

components:
  schemas:
    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - apiKey: []
